# Generated by Django 3.2.13 on 2022-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
