# Generated by Django 3.2.13 on 2022-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220526_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='scanned_id',
            field=models.FileField(upload_to='scanned_ids'),
        ),
    ]
